# Generated by Django 2.1.1 on 2018-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180923_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
