# Generated by Django 2.1.1 on 2018-11-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otrest', '0004_auto_20181125_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrecord',
            options={'ordering': ('-id',)},
        ),
    ]
