# Generated by Django 2.1.1 on 2018-11-28 22:57

from django.db import migrations, models
import otrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('otrest', '0005_auto_20181125_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrecord',
            name='certPic',
            field=models.ImageField(blank=True, upload_to=otrest.models.user_directory_path),
        ),
    ]
