# Generated by Django 2.1.1 on 2018-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrest', '0006_otrecord_certpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
