# Generated by Django 2.1.1 on 2019-07-28 22:01

from django.db import migrations, models
import otrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('otrest', '0008_auto_20181202_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrecord',
            name='certPic',
            field=models.FileField(blank=True, upload_to=otrest.models.user_directory_path),
        ),
    ]
