# Generated by Django 2.1.1 on 2019-07-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrest', '0009_auto_20190728_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrecord',
            name='endTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='otrecord',
            name='startTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
